#FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build
#
#WORKDIR /src
#COPY ["TestWeather/TestWeather.csproj", "TestWeather/"]
#RUN dotnet restore "TestWeather/TestWeather.csproj"
#COPY . .
#WORKDIR "/src"
#RUN dotnet build "TestWeather/TestWeather.csproj" -c Release -o /app/build
#RUN dotnet publish "TestWeather/TestWeather.csproj" -c Release -o /app/publish /p:UseAppHost=false
#
#FROM mcr.microsoft.com/dotnet/aspnet:7.0
#EXPOSE 80
#EXPOSE 443
#WORKDIR /app
#COPY --from=build /app/publish .
#ENTRYPOINT ["dotnet", "TestWeather.dll"]
#
#
#
#
FROM mcr.microsoft.com/dotnet/aspnet:7.0 AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build
ARG BUILD_CONFIGURATION=Release
WORKDIR /src
COPY ["TestWeather/TestWeather.csproj", "TestWeather/"]
RUN dotnet restore "./TestWeather/./TestWeather.csproj"
COPY . .
WORKDIR "/src/TestWeather"
RUN dotnet build "./TestWeather.csproj" -c $BUILD_CONFIGURATION -o /app/build

FROM build AS publish
ARG BUILD_CONFIGURATION=Release
RUN dotnet publish "./TestWeather.csproj" -c $BUILD_CONFIGURATION -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "TestWeather.dll"]

